# Generated by Django 5.2.1 on 2025-05-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_course_historicalcourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='expertisearea',
            options={'verbose_name': 'Área de expertise', 'verbose_name_plural': 'Áreas de expertise'},
        ),
        migrations.AlterModelOptions(
            name='historicalcourse',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Histórico', 'verbose_name_plural': 'historical Cursos'},
        ),
        migrations.AlterModelOptions(
            name='historicalexpertisearea',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Histórico', 'verbose_name_plural': 'historical Áreas de expertise'},
        ),
        migrations.AlterModelOptions(
            name='historicalinstitute',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Histórico', 'verbose_name_plural': 'historical Institutos'},
        ),
        migrations.AlterModelOptions(
            name='institute',
            options={'verbose_name': 'Instituto', 'verbose_name_plural': 'Institutos'},
        ),
    ]
