# Generated by Django 5.2.1 on 2025-05-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_historicalstudentprofile_studentprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprofessorprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Histórico', 'verbose_name_plural': 'historical Perfis dos Professores'},
        ),
        migrations.AlterModelOptions(
            name='historicalstudentprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Histórico', 'verbose_name_plural': 'historical Perfis dos Alunos'},
        ),
        migrations.AlterModelOptions(
            name='historicaluser',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Histórico', 'verbose_name_plural': 'historical Usuários'},
        ),
        migrations.AlterModelOptions(
            name='professorprofile',
            options={'verbose_name': 'Perfil do Professor', 'verbose_name_plural': 'Perfis dos Professores'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Perfil do Aluno', 'verbose_name_plural': 'Perfis dos Alunos'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
