# Generated by Django 5.2.3 on 2025-06-26 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_course_options_alter_expertisearea_options_and_more'),
        ('user', '0004_alter_historicalprofessorprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', related_query_name='student', to='academic.course', verbose_name='Curso'),
        ),
    ]
