# Generated by Django 5.2.3 on 2025-06-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_studentprofile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentprofile',
            name='enrollment',
            field=models.CharField(db_index=True, default='5d1477d1-c2ba-4870-b375-d8b6123411c3', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment',
            field=models.CharField(default='5d1477d1-c2ba-4870-b375-d8b6123411c3', max_length=50, unique=True),
        ),
    ]
