# Generated by Django 5.2.3 on 2025-07-06 21:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_historicalstudentprofile_enrollment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentprofile',
            name='enrollment',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
