# Generated by Django 5.2.3 on 2025-07-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_historicalstudentprofile_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofessorprofile',
            name='lattes_url',
            field=models.CharField(max_length=255, null=True, verbose_name='URL do Currículo Lattes'),
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='lattes_url',
            field=models.CharField(max_length=255, null=True, verbose_name='URL do Currículo Lattes'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='role',
            field=models.CharField(choices=[('PROFESSOR', 'Professor'), ('STUDENT', 'Student')], default='STUDENT', max_length=10, verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PROFESSOR', 'Professor'), ('STUDENT', 'Student')], default='STUDENT', max_length=10, verbose_name='Perfil'),
        ),
    ]
