# Generated by Django 5.2.3 on 2025-07-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_historicalprofessorprofile_lattes_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofessorprofile',
            name='biography',
            field=models.TextField(null=True, verbose_name='Biografia'),
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='biography',
            field=models.TextField(null=True, verbose_name='Biografia'),
        ),
    ]
