# Generated by Django 5.2.3 on 2025-07-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0005_remove_historicalsupervisionrequest_justification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsupervisionrequest',
            name='answer',
            field=models.CharField(choices=[('YES', 'Sim'), ('NO', 'Não'), ('NO_ANSWER', 'Sem Resposta')], default='NO_ANSWER', max_length=10, verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='supervisionrequest',
            name='answer',
            field=models.CharField(choices=[('YES', 'Sim'), ('NO', 'Não'), ('NO_ANSWER', 'Sem Resposta')], default='NO_ANSWER', max_length=10, verbose_name='Resposta'),
        ),
    ]
